package com.webapp.systemtest; // Generated by Selenium IDE

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.CapabilityType;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class AdminST {

  JavascriptExecutor js;
  private WebDriver driver;
  private Map<String, Object> vars;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void deleteUser() {
    // Test name: DeleteUser
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/user?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/user?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | chooseOkOnNextConfirmation |  |  |
    // 4 | click | css=tr:nth-child(1) .btn-danger |  |
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn-danger")).click();
    // 5 | assertConfirmation | 您确定要删除这个用户吗？ |  |
    assertEquals("您确定要删除这个用户吗？", driver.switchTo().alert().getText());
    // 6 | webdriverChooseOkOnVisibleConfirmation |  |  |
    driver.switchTo().alert().accept();
  }

  @Test
  public void homePage() {
    // Test name: HomePage
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/blank |  |
    driver.get("http://localhost:8080/MeetHere_war/blank");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | linkText=首页 |  |
    driver.findElement(By.linkText("首页")).click();
  }

  @Test
  public void modifyUser() {
    // Test name: ModifyUser
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/user?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/user?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | css=tr:nth-child(1) .btn-info |  |
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn-info")).click();
    // 4 | click | css=.row-fluid |  |
    driver.findElement(By.cssSelector(".row-fluid")).click();
    // 5 | type | id=username | 123 |
    driver.findElement(By.id("username")).sendKeys("123");
    // 6 | click | css=.data_form |  |
    driver.findElement(By.cssSelector(".data_form")).click();
    // 7 | click | css=tr:nth-child(2) |  |
    driver.findElement(By.cssSelector("tr:nth-child(2)")).click();
    // 8 | click | css=tr:nth-child(3) |  |
    driver.findElement(By.cssSelector("tr:nth-child(3)")).click();
    // 9 | click | css=.data_form |  |
    driver.findElement(By.cssSelector(".data_form")).click();
    // 10 | type | id=name | 123 |
    driver.findElement(By.id("name")).sendKeys("123");
    // 11 | click | id=sex |  |
    driver.findElement(By.id("sex")).click();
    // 12 | select | id=sex | label=女 |
    {
      WebElement dropdown = driver.findElement(By.id("sex"));
      dropdown.findElement(By.xpath("//option[. = '女']")).click();
    }
    // 13 | click | id=sex |  |
    driver.findElement(By.id("sex")).click();
    // 14 | click | id=tel |  |
    driver.findElement(By.id("tel")).click();
    // 15 | type | id=tel | 123 |
    driver.findElement(By.id("tel")).sendKeys("123");
    // 16 | click | css=.btn:nth-child(1) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }

  @Test
  public void modifyNews() {
    // Test name: ModifyNews
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/news?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/news?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | css=td > .btn-info |  |
    driver.findElement(By.cssSelector("td > .btn-info")).click();
    // 4 | click | css=.data_form |  |
    driver.findElement(By.cssSelector(".data_form")).click();
    // 5 | type | id=title | 456 |
    driver.findElement(By.id("title")).sendKeys("456");
    // 6 | type | id=author | 456 |
    driver.findElement(By.id("author")).sendKeys("456");
    // 7 | type | id=detail | 456 |
    driver.findElement(By.id("detail")).sendKeys("456");
    // 8 | click | css=.btn:nth-child(1) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }

  @Test
  public void deleteNews() {
    // Test name: DeleteNews
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/news?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/news?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | chooseOkOnNextConfirmation |  |  |
    // 4 | click | css=.btn-danger |  |
    driver.findElement(By.cssSelector(".btn-danger")).click();
    // 5 | assertConfirmation | 您确定要删除这条新闻吗？ |  |
    assertEquals("您确定要删除这条新闻吗？", driver.switchTo().alert().getText());
    // 6 | webdriverChooseOkOnVisibleConfirmation |  |  |
    driver.switchTo().alert().accept();
  }

  @Test
  public void createNews() {
    // Test name: CreateNews
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/news?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/news?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | css=.btn |  |
    driver.findElement(By.cssSelector(".btn")).click();
    // 4 | click | id=title |  |
    driver.findElement(By.id("title")).click();
    // 5 | type | id=title | 123 |
    driver.findElement(By.id("title")).sendKeys("123");
    // 6 | type | id=author | 123 |
    driver.findElement(By.id("author")).sendKeys("123");
    // 7 | click | id=detail |  |
    driver.findElement(By.id("detail")).click();
    // 8 | type | id=detail | 123 |
    driver.findElement(By.id("detail")).sendKeys("123");
    // 9 | click | css=.btn:nth-child(1) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }

  @Test
  public void deleteUnverifiedComment() {
    // Test name: DeleteUnverifiedComment
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/comment?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/comment?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | chooseOkOnNextConfirmation |  |  |
    // 4 | click | css=.btn:nth-child(2) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 5 | assertConfirmation | 您确定要删除这条留言吗？ |  |
    assertEquals("您确定要删除这条留言吗？", driver.switchTo().alert().getText());
    // 6 | webdriverChooseOkOnVisibleConfirmation |  |  |
    driver.switchTo().alert().accept();
  }

  @Test
  public void deleteVerifiedComment() {
    // Test name: DeleteVerifiedComment
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/comment?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/comment?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | chooseOkOnNextConfirmation |  |  |
    // 4 | click | css=div:nth-child(2) > .table .btn |  |
    driver.findElement(By.cssSelector("div:nth-child(2) > .table .btn")).click();
    // 5 | assertConfirmation | 您确定要删除这条留言吗？ |  |
    assertEquals("您确定要删除这条留言吗？", driver.switchTo().alert().getText());
    // 6 | webdriverChooseOkOnVisibleConfirmation |  |  |
    driver.switchTo().alert().accept();
  }

  @Test
  public void verifyComment() {
    // Test name: VerifyComment
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/comment?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/comment?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | chooseOkOnNextConfirmation |  |  |
    // 4 | click | css=tr:nth-child(1) .btn:nth-child(1) |  |
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn:nth-child(1)")).click();
    // 5 | assertConfirmation | 您确定要通过这条留言吗？ |  |
    assertEquals("您确定要通过这条留言吗？", driver.switchTo().alert().getText());
    // 6 | webdriverChooseOkOnVisibleConfirmation |  |  |
    driver.switchTo().alert().accept();
  }

  @Test
  public void addBuilding() {
    // Test name: AddBuilding
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/building?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/building?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | css=.btn |  |
    driver.findElement(By.cssSelector(".btn")).click();
    // 4 | click | id=buildingName |  |
    driver.findElement(By.id("buildingName")).click();
    // 5 | type | id=buildingName | 123 |
    driver.findElement(By.id("buildingName")).sendKeys("123");
    // 6 | type | id=buildingPrice | 123 |
    driver.findElement(By.id("buildingPrice")).sendKeys("123");
    // 7 | type | id=buildingDescription | 123 |
    driver.findElement(By.id("buildingDescription")).sendKeys("123");
    // 8 | click | css=.btn:nth-child(1) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }

  @Test
  public void deleteBuilding() {
    // Test name: DeleteBuilding
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/building?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/building?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | chooseOkOnNextConfirmation |  |  |
    // 4 | click | css=.btn-danger |  |
    driver.findElement(By.cssSelector(".btn-danger")).click();
    // 5 | assertConfirmation | 您确定要删除这个楼吗？ |  |
    assertEquals("您确定要删除这个楼吗？", driver.switchTo().alert().getText());
    // 6 | webdriverChooseOkOnVisibleConfirmation |  |  |
    driver.switchTo().alert().accept();
  }

  @Test
  public void modifyBuilding() {
    // Test name: ModifyBuilding
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/building?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/building?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | css=td > .btn-info |  |
    driver.findElement(By.cssSelector("td > .btn-info")).click();
    // 4 | click | css=.data_form |  |
    driver.findElement(By.cssSelector(".data_form")).click();
    // 5 | type | id=buildingName | 456 |
    driver.findElement(By.id("buildingName")).sendKeys("456");
    // 6 | type | id=buildingPrice | 456 |
    driver.findElement(By.id("buildingPrice")).sendKeys("456");
    // 7 | type | id=buildingDescription | 456 |
    driver.findElement(By.id("buildingDescription")).sendKeys("456");
    // 8 | click | css=.btn:nth-child(1) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }

  @Test
  public void deleteUnverifiedRecord() {
    // Test name: DeleteUnverifiedRecord
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/record?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/record?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | chooseOkOnNextConfirmation |  |  |
    // 4 | click | css=.btn:nth-child(2) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 5 | assertConfirmation | 您确定要删除这条记录吗？ |  |
    assertEquals("您确定要删除这条记录吗？", driver.switchTo().alert().getText());
    // 6 | webdriverChooseOkOnVisibleConfirmation |  |  |
    driver.switchTo().alert().accept();
  }

  @Test
  public void verifyRecord() {
    // Test name: VerifyRecord
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/record?action=list |  |
    driver.get("http://localhost:8080/MeetHere_war/record?action=list");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | chooseOkOnNextConfirmation |  |  |
    // 4 | click | css=tr:nth-child(1) .btn:nth-child(1) |  |
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn:nth-child(1)")).click();
    // 5 | assertConfirmation | 您确定审核通过这条记录吗？ |  |
    assertEquals("您确定审核通过这条记录吗？", driver.switchTo().alert().getText());
    // 6 | webdriverChooseOkOnVisibleConfirmation |  |  |
    driver.switchTo().alert().accept();
  }

  @Test
  public void changePassword() {
    // Test name: ChangePassword
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/password?action=change |  |
    driver.get("http://localhost:8080/MeetHere_war/password?action=change");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | id=oldPassword |  |
    driver.findElement(By.id("oldPassword")).click();
    // 4 | type | id=oldPassword | root |
    driver.findElement(By.id("oldPassword")).sendKeys("root");
    // 5 | type | id=newPassword | root |
    driver.findElement(By.id("newPassword")).sendKeys("root");
    // 6 | type | id=rPassword | root |
    driver.findElement(By.id("rPassword")).sendKeys("root");
    // 7 | sendKeys | id=rPassword | ${KEY_ENTER} |
    driver.findElement(By.id("rPassword")).sendKeys(Keys.ENTER);
  }

  @Test
  public void clickMenu() {
    // Test name: ClickMenu
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/blank |  |
    driver.get("http://localhost:8080/MeetHere_war/blank");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | linkText=首页 |  |
    driver.findElement(By.linkText("首页")).click();
    // 4 | click | linkText=用户管理 |  |
    driver.findElement(By.linkText("用户管理")).click();
    // 5 | click | linkText=新闻管理 |  |
    driver.findElement(By.linkText("新闻管理")).click();
    // 6 | click | linkText=留言管理 |  |
    driver.findElement(By.linkText("留言管理")).click();
    // 7 | click | linkText=场地管理 |  |
    driver.findElement(By.linkText("场地管理")).click();
    // 8 | click | linkText=预约管理 |  |
    driver.findElement(By.linkText("预约管理")).click();
    // 9 | click | linkText=修改密码 |  |
    driver.findElement(By.linkText("修改密码")).click();
    // 10 | click | linkText=退出系统 |  |
    driver.findElement(By.linkText("退出系统")).click();
  }
}
