package systemTest; // Generated by Selenium IDE

import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class LoginSignUpTestTest {

  JavascriptExecutor js;
  private WebDriver driver;
  private Map<String, Object> vars;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void loginFail() {
    // Test name: LoginFail
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/ |  |
    driver.get("http://localhost:8080/MeetHere_war/");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | id=username |  |
    driver.findElement(By.id("username")).click();
    // 4 | type | id=username | 123 |
    driver.findElement(By.id("username")).sendKeys("123");
    // 5 | type | id=password | 123 |
    driver.findElement(By.id("password")).sendKeys("123");
    // 6 | click | css=.btn:nth-child(1) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }

  @Test
  public void loginSucceedAdmin() {
    // Test name: LoginSucceedAdmin
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/ |  |
    driver.get("http://localhost:8080/MeetHere_war/");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | id=username |  |
    driver.findElement(By.id("username")).click();
    // 4 | type | id=username | root |
    driver.findElement(By.id("username")).sendKeys("root");
    // 5 | type | id=password | root |
    driver.findElement(By.id("password")).sendKeys("root");
    // 6 | click | css=.btn:nth-child(1) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }

  @Test
  public void loginSucceedUser() {
    // Test name: LoginSucceedUser
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/ |  |
    driver.get("http://localhost:8080/MeetHere_war/");
    // 2 | setWindowSize | 1052x554 |  |
    driver.manage().window().setSize(new Dimension(1052, 554));
    // 3 | click | id=username |  |
    driver.findElement(By.id("username")).click();
    // 4 | type | id=username | pjt |
    driver.findElement(By.id("username")).sendKeys("pjt");
    // 5 | type | id=password | pjt |
    driver.findElement(By.id("password")).sendKeys("pjt");
    // 6 | sendKeys | id=password | ${KEY_ENTER} |
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
  }

  @Test
  public void signUp() {
    // Test name: SignUp
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/MeetHere_war/ |  |
    driver.get("http://localhost:8080/MeetHere_war/");
    // 2 | setWindowSize | 1054x556 |  |
    driver.manage().window().setSize(new Dimension(1054, 556));
    // 3 | click | css=.btn:nth-child(3) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
    // 4 | click | id=username |  |
    driver.findElement(By.id("username")).click();
    // 5 | type | id=username | 123 |
    driver.findElement(By.id("username")).sendKeys("123");
    // 6 | type | id=name | 123 |
    driver.findElement(By.id("name")).sendKeys("123");
    // 7 | type | id=password | 123 |
    driver.findElement(By.id("password")).sendKeys("123");
    // 8 | click | css=.radio:nth-child(6) |  |
    driver.findElement(By.cssSelector(".radio:nth-child(6)")).click();
    // 9 | click | id=tel |  |
    driver.findElement(By.id("tel")).click();
    // 10 | type | id=tel | 123 |
    driver.findElement(By.id("tel")).sendKeys("123");
    // 11 | click | css=.btn:nth-child(1) |  |
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }
}
